### ISSUE TITLE
Splash screen according to selected theme

### ISSUE THREAD

**Issue by staticssleever668** [barbeau/gpstest#431] opened 2020-08-27 10:06 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes when you open the app in the dark you may see a flashing white screen even if a dark theme is selected - pretty disturbing

**Describe the solution you'd like**
I want this app to have splash screens for dark and light themes accordingly - when dark theme is used then show a dark splash, if light theme is used then show a light splash  

**Describe alternatives you've considered**
Only dark splash screen may be added, but that may disturb some people with light themes

**Additional context**
As with adaptive icon, this is supported by most of modern apps

**Comment by barbeau** [comment] 2020-08-27 17:12
Thanks for the feedback @staticssleever668! I agree, this is annoying. FWIW, this isn't an intentional choice, but how Android launches activities prior to the official dark mode support - so something I couldn't control when I initially implemented dark mode in GPSTest. But hopefully it should be resolved when I switch to official dark mode support.

This is a duplicate of https://github.com/barbeau/gpstest/issues/357, so I'm going to close this issue out. Please feel free to give a thumbs up on https://github.com/barbeau/gpstest/issues/357.

**Closed by barbeau** 2020-08-27 17:12 UTC
Labels: enhancement
