### ISSUE TITLE
On-off button  could be clearer

### ISSUE THREAD

**Issue by jidanni** [barbeau/gpstest#396] opened 2020-04-28 07:19 UTC
Okay, I finally figured out what that switch at the top of the screen does.
But consider using a more familiar on-off button. One that becomes a square or a circle.
Currently just looking at it it's hard to tell which position is on and which position is off.

**Comment by jidanni** [comment] 2020-04-28 07:22
An even bigger problem is it moves around depending on which page you're looking at.
Sometimes it's at the most right part of the screen, but sometimes it gets shoved around by a share button or a menu button. Please be consistent in where you put it.

**Comment by barbeau** [comment] 2020-04-28 20:47
@jidanni Thanks for the feedback! Closing as duplicate of https://github.com/barbeau/gpstest/issues/325.

**Closed by barbeau** 2020-04-28 20:47 UTC
Labels: duplicate
