### ISSUE TITLE
Crash in Accuracy mode

### ISSUE THREAD

**Issue by Saboe** [barbeau/gpstest#459] opened 2020-12-15 14:56 UTC
When I start the accuracy mode everything seems to be OK so far but after a while, mostly between 15 and 40 seconds GPStest crashes. The time until crash differs from time to time, I've no clue where it depends on.

My phone is a Fairphone 3 with Android 10.

**Comment by barbeau** [comment] 2020-12-15 19:07
@Saboe Thanks for the report! Is this using the version from F-Droid or Google Play? Are you using app version v3.9.1, and if so is it new to the app version v3.9.1?

**Comment by Saboe** [comment] 2020-12-15 22:27
I'm using the F-Droid version 3.9.1 on my Fairphone 3 with Android 10, build 8901.3.A.0054.20200929.

This bug is **not** new to this version. I've experienced this bug several month ago (but took no action to report this).

**Comment by barbeau** [comment] 2020-12-16 00:08
@Saboe ok, thanks! I think this is a duplicate of https://github.com/barbeau/gpstest/issues/458, so I'm going to close this and will post more to the other issue.

**Closed by barbeau** 2020-12-16 00:08 UTC
Labels: bug, duplicate
