### ISSUE TITLE
 Separate "used in fix" group better

### ISSUE THREAD

**Issue by jidanni** [barbeau/gpstest#402] opened 2020-04-28 08:15 UTC
If one chooses Sort by: used in fix, on the status page... how about adding a bar separating the ones that are used in the fix, and the ones that are not.

**Comment by barbeau** [comment] 2020-04-29 17:04
@jidanni Thanks for the feedback! The "U" flag indicates which satellites are used in a fix. Closing this as a duplicate of https://github.com/barbeau/gpstest/issues/322.

**Closed by barbeau** 2020-04-29 17:04 UTC
