### ISSUE TITLE
gps not turned off when 'closing' app

### ISSUE THREAD

**Issue by spaetz** [barbeau/gpstest#297] opened 2019-06-05 19:34 UTC
**Summary:**
While gpstest is running, the location icon is shown, ie the gps is turned on. When closing the app by pressing the home button or the 'app switch button', the icon is still shown and battery drains quicker. As soon as the app is 'swipe-closed' in the app overview or it is force-closed in the app details page, the location icon disappears.

**Expected behavior:** 
When gpstest is not in the foreground it should not keep the gps turned on.

**Observed behavior:** 
As long as the app is somehow active in the background, it keeps the gps turned on.

**Device and Android version:** 
Aquaris U plus (tenshi), LineageOS 14.1, no gapps.

Thanks for GPStest, it is really useful.

**Comment by goldfndr** [comment] 2019-06-06 00:39
Duplicate of #237; look in GPSTest's Settings for a "Stop GNSS in background" (or translated equivalent) near the bottom in the "GNSS" category.

(Also, see [my comment](https://github.com/barbeau/gpstest/issues/237#issuecomment-439209286) about how pressing Home isn't an Android method of closing an app, it puts the app in the background; the Back button can be used to close an app.)

**Comment by barbeau** [comment] 2019-06-10 16:01
Thanks for the feedback!  Yes, I'm closing this as a duplicate of https://github.com/barbeau/gpstest/issues/237, but I'll comment further there on a better implementation of background activity.

**Closed by barbeau** 2019-06-10 16:01 UTC
Labels: duplicate
